# Generated by Django 3.2.8 on 2024-09-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
